### ISSUE TITLE
png logo

### ISSUE THREAD

**Issue by Null-B** [filipgaming008/epik-bot#3]
![onlinelogomaker-060121-1359-8932-2000-transparent](https://user-images.githubusercontent.com/76712316/120320470-83871e80-c2e2-11eb-8121-52b5f73ad25c.png)

**Comment by PH-KDX** [comment]
Not so good on dark theme.

![image](https://user-images.githubusercontent.com/50588793/120321110-30fa3200-c2e3-11eb-8cb4-f4bcec0b9d02.png)

**Comment by Null-B** [comment]
no shit

**Comment by Null-B** [comment]
![onlinelogomaker-060121-1359-8932-500](https://user-images.githubusercontent.com/76712316/120322979-4bcda600-c2e5-11eb-9c59-327dc73a9448.jpg)
here is a wihte vesion

**Comment by Null-B** [comment]
![Uploading onlinelogomaker-060121-1422-0691-2000-transparent.png…]()

**Comment by PH-KDX** [comment]
That works.
Or you could make the black text gray; would look less ugly.

**Comment by Null-B** [comment]
to late

**Comment by Null-B** [comment]
![onlinelogomaker-060121-1422-0691-2000-transparent](https://user-images.githubusercontent.com/76712316/120323740-1aa1a580-c2e6-11eb-9775-059d164edb3a.png)

**Comment by Null-B** [comment]
do you like the last one

**Comment by PH-KDX** [comment]
I can read it, which is a good thing.
So yeah, I guess.

**Comment by PH-KDX** [comment]
Although the combination of that with the other thing with white background is not so nice.

**Comment by PH-KDX** [comment]
Maybe try to change the black text into a different colour so you can rid of the white background.

**Comment by Null-B** [comment]
![onlinelogomaker-060121-1505-2189-2000-transparent](https://user-images.githubusercontent.com/76712316/120328163-dc5ab500-c2ea-11eb-8035-9c35ecdd0412.png)

**Comment by Null-B** [comment]
![onlinelogomaker-060121-1510-2614-2000-transparent](https://user-images.githubusercontent.com/76712316/120328916-9ce09880-c2eb-11eb-9e27-db666bfda80e.png)
